services:

  mysql_db1:
    image: mysql:latest
    container_name: mysql_db1
    environment:
      MYSQL_ROOT_PASSWORD: orders-password
      MYSQL_DATABASE: orders_db
    volumes:
      - orders_db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33061:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-microservice:
    build:
      context: ./orders
      dockerfile: Dockerfile
    container_name: orders-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db1:3306/orders_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=orders-password
    depends_on:
      mysql_db1:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8081:8080"

  mysql_db2:
    image: mysql:latest
    container_name: mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: users-password
      MYSQL_DATABASE: users_db
    volumes:
      - users_db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33062:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  users-microservice:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db2:3306/users_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=users-password
    depends_on:
      mysql_db2:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8082:8080"

  products_db:
    image: mongo:latest
    container_name: products_db
    environment:
      MONGO_INITDB_DATABASE: products_db
    volumes:
      - products_db_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  products-microservice:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: products-microservice
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://products_db:27017/products_db
    depends_on:
      - products_db
    networks:
      - app-network
    ports:
      - "8083:8080"

networks:
  app-network:
    driver: bridge

volumes:
  orders_db_data:
  users_db_data:
  products_db_data:
